"""``conjured.agent`` — the Agent surface component.

The C4 responsibility is owned at ``conjured/docs/architecture/components.md``
§ Agent surface (cited, not quoted — a verbatim quote goes stale silently): the
in-package machine-readable companion surface at
``importlib.resources.files("conjured.agent")``, read by coding agents — the
agent-audience docs projection and its structured companions, each companion's
shape owned by the reference that defines it.

The surface helps agents by **steering** (not findability — agents grep to target);
steering rides on violation messages and contrastive-redirects, derived empirically
from where a fresh agent lands.

**What ships from this package** — it is the ``importlib.resources`` anchor for all of it:

- ``llms.txt`` — the index of the surface.
- ``docs/`` — the filtered, frontmatter-stripped projection of the canonical docs.
- ``steering/`` — the steering content (violation messages + contrastive redirects).
- ``error-classes.toml`` — the machine-readable audit_code → rule mapping, generated by
  ``tools/gen_error_index.py``.

(The conformance audit prompts are a separate surface — they ship from
``conjured.conformance``.)
"""
